import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      /* ── Colors: exact values from DESIGN.md Tailwind config block ── */
      colors: {
        "secondary-fixed": "#d8e3f9",
        "secondary-fixed-dim": "#cad5ea",
        "on-primary": "#fff7f5",
        "tertiary": "#755b25",
        "inverse-primary": "#ff6e41",
        "tertiary-fixed": "#f9d593",
        "secondary-container": "#d8e3f9",
        "on-background": "#2d3335",
        "tertiary-container": "#f9d593",
        "primary-fixed-dim": "#ed6235",
        "primary-dim": "#9b2b00",
        "surface-bright": "#f8f9fa",
        "surface-variant": "#dee3e6",
        "on-secondary-container": "#475264",
        "outline": "#767c7e",
        "tertiary-dim": "#684f1a",
        "inverse-surface": "#0c0f10",
        "surface-container-lowest": "#ffffff",
        "error": "#a83836",
        "on-secondary-fixed-variant": "#515c6e",
        "surface-container-low": "#f1f4f5",
        "on-tertiary-fixed": "#4c3602",
        "error-dim": "#67040d",
        "on-surface": "#2d3335",
        "on-secondary": "#f8f8ff",
        "tertiary-fixed-dim": "#eac787",
        "surface-container": "#ebeef0",
        "outline-variant": "#adb3b5",
        "inverse-on-surface": "#9b9d9e",
        "on-tertiary-container": "#614914",
        "surface": "#f8f9fa",
        "on-tertiary-fixed-variant": "#6b521d",
        "error-container": "#fa746f",
        "surface-tint": "#ad3507",
        "primary": "#ad3507",
        "on-secondary-fixed": "#354051",
        "primary-container": "#ff6e41",
        "on-primary-fixed": "#000000",
        "secondary": "#556072",
        "on-primary-fixed-variant": "#4e1100",
        "on-error-container": "#6e0a12",
        "secondary-dim": "#495465",
        "on-primary-container": "#3d0b00",
        "primary-fixed": "#ff6e41",
        "on-surface-variant": "#5a6062",
        "surface-container-highest": "#dee3e6",
        "background": "#f8f9fa",
        "surface-container-high": "#e5e9eb",
        "on-error": "#fff7f6",
        "surface-dim": "#d5dbdd",
        "on-tertiary": "#fff8f1",
        // Semantic aliases for existing code compat
        ink: "#2d3335",
        dark: "#2d3335",
        mid: "#5a6062",
        muted: "#767c7e",
        subtle: "#adb3b5",
        pale: "#f1f4f5",
        alabaster: "#ebeef0",
        payne: "#2d3335",
        light: "rgba(173, 179, 181, 0.15)",
        brand: {
          orange: "#ad3507",
          "orange-hover": "#9b2b00",
          "orange-pale": "#fff0e6",
          "orange-mid": "#ffcaa7",
        },
        heading: "#2d3335",
      },

      /* ── Border Radius: exact values from DESIGN.md ── */
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },

      /* ── Font Family: exact values from DESIGN.md ── */
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
        display: ["Manrope"],
        // Compat aliases
        sans: ["Inter", "var(--font-inter)", "DM Sans", "sans-serif"],
        mono: ["var(--font-dm-mono)", "monospace"],
      },

      /* ── Additional scales ── */
      width: {
        sidebar: "220px",
      },
      height: {
        topbar: "52px",
      },
      fontSize: {
        "display-lg": ["3.5rem", { lineHeight: "1.1", fontWeight: "800" }],
        "display-md": ["2.5rem", { lineHeight: "1.15", fontWeight: "800" }],
        "headline-lg": ["2rem", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["1.75rem", { lineHeight: "1.25", fontWeight: "700" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.3", fontWeight: "700" }],
        "title-lg": ["1.125rem", { lineHeight: "1.35", fontWeight: "600" }],
        "title-md": ["1rem", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["1rem", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["0.875rem", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.55", fontWeight: "400" }],
        "label-lg": ["0.875rem", { lineHeight: "1.4", fontWeight: "600" }],
        "label-md": ["0.75rem", { lineHeight: "1.4", fontWeight: "600" }],
        "label-sm": ["0.6875rem", { lineHeight: "1.4", fontWeight: "500" }],
      },
      boxShadow: {
        "ambient-sm": "0 2px 20px rgba(45, 51, 53, 0.04)",
        "ambient": "0 4px 32px rgba(45, 51, 53, 0.05)",
        "ambient-lg": "0 8px 48px rgba(45, 51, 53, 0.06)",
        "float": "0 12px 60px rgba(45, 51, 53, 0.08)",
        "ghost": "inset 0 0 0 1px rgba(173, 179, 181, 0.15)",
      },
    },
  },
  plugins: [],
};
export default config;
