/**
 * Write branditect-ui/spec/i18n-gap.md: every user-facing string in the app
 * shell that has no dictionary key, grouped by the screen it appears on.
 *
 * This is the half of inbox entry 3 that cannot be done here. The entry says
 * "do not invent Finnish", and the dictionary covers a small fraction of what
 * is actually on screen, so the honest deliverable is the list rather than a
 * thousand strings of my Finnish. Nothing is truncated: a capped list would
 * read as the whole job.
 *
 * Usage: npm run i18n:gap
 */
import { readdirSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { findAllLiterals } from "../lib/i18n-scan.ts";
import { SCOPE, OUT_OF_SCOPE } from "../lib/i18n-scope.ts";
import { en } from "../lib/i18n/en.ts";

function walk(dir) {
  const out = [];
  let entries;
  try { entries = readdirSync(dir); } catch { return out; }
  for (const e of entries) {
    const p = join(dir, e);
    if (OUT_OF_SCOPE.some((x) => p.startsWith(x))) continue;
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (e.endsWith(".tsx")) out.push(p);
  }
  return out;
}

const norm = (s) => s.trim().replace(/\s+/g, " ");
const known = new Set(Object.values(en).map(norm));

const files = SCOPE.flatMap(walk).sort();
const sections = [];
let strings = 0, keyed = 0;

for (const f of files) {
  const seen = new Set();
  const rows = [];
  for (const l of findAllLiterals(readFileSync(f, "utf8"))) {
    const t = norm(l.text);
    if (seen.has(t)) continue;
    seen.add(t);
    if (known.has(t)) { keyed++; continue; }
    rows.push(t);
    strings++;
  }
  if (rows.length) sections.push({ f, rows });
}

const lines = [
  "# The interface strings that have no key",
  "",
  "Generated by `npm run i18n:gap`. Do not edit by hand — regenerate it.",
  "",
  "Inbox entry 3 says the dictionary was derived from the real strings in these",
  "files. Measured against them, most of the interface is not in it: the strings",
  "below appear on screen and match no value in `lib/i18n/en.ts`.",
  "",
  `**${strings} distinct strings across ${sections.length} files.** A further ${keyed} already`,
  "match a key and were extracted or are ready to be.",
  "",
  "Nothing here is truncated. A list that stopped at the first hundred would read",
  "as the whole job.",
  "",
  "The marketing site under `app/(site)` is not included: English by Saara's",
  "decision.",
  "",
];

for (const { f, rows } of sections) {
  lines.push(`## ${f}`, "", ...rows.map((r) => `- ${r.replace(/\|/g, "\\|")}`), "");
}

writeFileSync("branditect-ui/spec/i18n-gap.md", lines.join("\n"));
console.log(`${strings} distinct strings across ${sections.length} files → branditect-ui/spec/i18n-gap.md`);
